<a href="https://colab.research.google.com/github/shaurya25007212-droid/MLE/blob/main/Completed_Lab1_Practice_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI201B — Machine Learning Essentials
## Lab 1: Practice Exercises — NumPy & Pandas

These are **for you to solve independently**, after going through the `Lab1_NumPy_Pandas_Refresher` notebook. No worked examples here — just problems. Write your code in the empty cell under each question.

- Questions 1–6: NumPy
- Questions 7–14: Pandas, using the same housing dataset from Lab 1
- Questions 15–17: Missing values
- Questions 18–19: Mini challenge (combine everything)

Run the setup cell below first.

In [ ]:
import numpy as np
import pandas as pd

# Recreate the same housing dataset from Lab 1 so this notebook runs on its own
housing_data = {
    "area_sqft":     [650, 800, 1200, 950, 1500, 700, 1100, 1800, 900, 1300,
                       600, 1050, 1600, 750, 1400, 1000, 1250, 850, 1700, 950],
    "bedrooms":      [1, 2, 3, 2, 3, 1, 2, 4, 2, 3,
                       1, 2, 3, 2, 3, 2, 3, 2, 4, 2],
    "bathrooms":     [1, 1, 2, 2, 2, 1, 2, 3, 1, 2,
                       1, 2, 2, 1, 2, 2, 2, 1, 3, 2],
    "age_years":     [5, 12, 8, 20, 3, 15, 10, 2, 18, 7,
                       25, 9, 4, 14, 6, 11, 8, 16, 1, 13],
    "locality":      ["Vaishali Nagar", "Malviya Nagar", "C-Scheme", "Mansarovar", "C-Scheme",
                       "Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Mansarovar", "Malviya Nagar",
                       "Mansarovar", "Vaishali Nagar", "C-Scheme", "Malviya Nagar", "C-Scheme",
                       "Vaishali Nagar", "Malviya Nagar", "Mansarovar", "C-Scheme", "Vaishali Nagar"],
    "price_lakhs":   [32, 42, 78, 55, 105, 35, 68, 145, 52, 82,
                       28, 62, 115, 40, 98, 58, 75, 48, 135, 56],
}
df = pd.DataFrame(housing_data)
print("Dataset ready:", df.shape)
df.head()

Dataset ready: (20, 6)

   area_sqft  bedrooms  bathrooms  age_years        locality  price_lakhs
0        650         1          1          5  Vaishali Nagar           32
1        800         2          1         12   Malviya Nagar           42
2       1200         3          2          8        C-Scheme           78
3        950         2          2         20      Mansarovar           55
4       1500         3          2          3        C-Scheme          105

---
## Section A: NumPy

**Q1.** Create a NumPy array `temps` holding these 7 daily temperatures (°C): `[31, 33, 29, 35, 32, 28, 30]`.
Print the mean, max, min, and standard deviation.

**Q1.** Create a NumPy array `temps` containing the seven daily temperatures: `[31, 33, 29, 35, 32, 28, 30]`. Print its mean, maximum, minimum, and standard deviation.

In [ ]:
# Q1
temps = np.array([31, 33, 29, 35, 32, 28, 30])

print("Mean:", np.mean(temps))
print("Maximum:", np.max(temps))
print("Minimum:", np.min(temps))
print("Standard Deviation:", np.std(temps))

Mean: 31.142857142857142
Maximum: 35
Minimum: 28
Standard Deviation: 2.2314999074019015

**Q2.** Create a 4×4 array `mat` containing the numbers 1 to 16 (in order), using `np.arange` and `.reshape()`.
Print `mat`, then print just its second row and its last column.

In [ ]:
# Q2
mat = np.arange(1, 17).reshape(4, 4)

print(mat)
print("Second row:", mat[1])
print("Last column:", mat[:, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second row: [5 6 7 8]
Last column: [ 4  8 12 16]

**Q3.** Given `arr = np.array([5, 12, 8, 21, 3, 17, 9])`, use **boolean indexing** (no loops) to create a new array
`big_vals` containing only the values greater than 10.

In [ ]:
# Q3
arr = np.array([5, 12, 8, 21, 3, 17, 9])
big_vals = arr[arr > 10]

print(big_vals)

[12 21 17]

**Q4.** Two arrays represent 5 students' marks in two tests: `test1 = np.array([65, 70, 55, 80, 90])` and
`test2 = np.array([72, 68, 60, 85, 95])`. Using broadcasting (no loops), compute an array `average_marks`
holding each student's average of the two tests.

In [ ]:
# Q4
test1 = np.array([65, 70, 55, 80, 90])
test2 = np.array([72, 68, 60, 85, 95])

average_marks = (test1 + test2) / 2
print(average_marks)

[68.5 69.  57.5 82.5 92.5]

**Q5.** Create a 3×3 array of random integers between 1 and 50 using `np.random.randint` (use `np.random.seed(42)`
first so your output is reproducible). Print the array, then print the sum along each row (`axis=1`) and the sum
along each column (`axis=0`).

In [ ]:
# Q5
np.random.seed(42)
rand_mat = np.random.randint(1, 51, size=(3, 3))

print(rand_mat)
print("Row sums:", rand_mat.sum(axis=1))
print("Column sums:", rand_mat.sum(axis=0))

[[39 29 15]
 [43  8 21]
 [39 19 23]]
Row sums: [83 72 81]
Column sums: [121  56  59]

**Q6.** Stack two 1D arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])` into a single 2×3 array using
`np.vstack`. Then stack them into a 3×2 array using `np.column_stack` (or `np.vstack` + `.T`).

In [ ]:
# Q6
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("2x3 array:")
print(np.vstack((a, b)))

print("3x2 array:")
print(np.column_stack((a, b)))

2x3 array:
[[1 2 3]
 [4 5 6]]
3x2 array:
[[1 4]
 [2 5]
 [3 6]]

---
## Section B: Pandas — using the housing dataset (`df`)

**Q7.** Print the number of rows and columns in `df`, and list the column names.

In [ ]:
# Q7
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Column names:", df.columns.tolist())

Rows: 20
Columns: 6
Column names: ['area_sqft', 'bedrooms', 'bathrooms', 'age_years', 'locality', 'price_lakhs']

**Q8.** Select and display only the `area_sqft` and `price_lakhs` columns for houses located in **"Malviya Nagar"**.

In [ ]:
# Q8
print(df.loc[df["locality"] == "Malviya Nagar", ["area_sqft", "price_lakhs"]])

    area_sqft  price_lakhs
1         800           42
5         700           35
9        1300           82
13        750           40
16       1250           75

**Q9.** Create a new column `price_per_sqft` in `df` equal to `price_lakhs` (in lakhs) converted to rupees per
square foot. (1 lakh = 100,000 rupees, so `price_per_sqft = (price_lakhs * 100000) / area_sqft`.)
Display the 5 houses with the **highest** `price_per_sqft`.

In [ ]:
# Q9
df["price_per_sqft"] = (df["price_lakhs"] * 100000) / df["area_sqft"]

print(df.nlargest(5, "price_per_sqft")[["locality", "area_sqft", "price_lakhs", "price_per_sqft"]])

    locality  area_sqft  price_lakhs  price_per_sqft
7   C-Scheme       1800          145     8055.555556
18  C-Scheme       1700          135     7941.176471
12  C-Scheme       1600          115     7187.500000
4   C-Scheme       1500          105     7000.000000
14  C-Scheme       1400           98     7000.000000

**Q10.** Using `.groupby()`, find the average `price_lakhs` and average `area_sqft` **per locality**, sorted from
highest to lowest average price.

In [ ]:
# Q10
locality_avg = (
    df.groupby("locality")[["price_lakhs", "area_sqft"]]
      .mean()
      .sort_values("price_lakhs", ascending=False)
)

print(locality_avg)

                price_lakhs    area_sqft
locality
C-Scheme         112.666667  1533.333333
Vaishali Nagar    55.200000   950.000000
Malviya Nagar     54.800000   960.000000
Mansarovar        45.750000   825.000000

**Q11.** Count how many houses have **more than 2 bathrooms**, and separately, how many houses are **older than
15 years**.

In [ ]:
# Q11
print("Houses with more than 2 bathrooms:", (df["bathrooms"] > 2).sum())
print("Houses older than 15 years:", (df["age_years"] > 15).sum())

Houses with more than 2 bathrooms: 2
Houses older than 15 years: 4

**Q12.** Create a new column `size_category` in `df`: `"Small"` if `area_sqft < 900`, `"Medium"` if
`900 <= area_sqft < 1400`, and `"Large"` otherwise. (Hint: `np.select` or a small function with `.apply()`.)

In [ ]:
# Q12
conditions = [
    df["area_sqft"] < 900,
    (df["area_sqft"] >= 900) & (df["area_sqft"] < 1400)
]
choices = ["Small", "Medium"]

df["size_category"] = np.select(conditions, choices, default="Large")
print(df[["area_sqft", "size_category"]])

    area_sqft size_category
0         650         Small
1         800         Small
2        1200        Medium
3         950        Medium
4        1500         Large
5         700         Small
6        1100        Medium
7        1800         Large
8         900        Medium
9        1300        Medium
10        600         Small
11       1050        Medium
12       1600         Large
13        750         Small
14       1400         Large
15       1000        Medium
16       1250        Medium
17        850         Small
18       1700         Large
19        950        Medium

**Q13.** Sort `df` by `price_lakhs` in descending order and display only the top 5 rows, showing just the
`locality`, `area_sqft`, and `price_lakhs` columns.

In [ ]:
# Q13
print(
    df.sort_values("price_lakhs", ascending=False)
      .head(5)[["locality", "area_sqft", "price_lakhs"]]
)

    locality  area_sqft  price_lakhs
7   C-Scheme       1800          145
18  C-Scheme       1700          135
12  C-Scheme       1600          115
4   C-Scheme       1500          105
14  C-Scheme       1400           98

**Q14.** Using `.corr()`, find which single numeric feature has the **strongest correlation with `price_lakhs`**.
Print the full correlation of every numeric column against `price_lakhs` only (not the whole matrix).

In [ ]:
# Q14
correlations = df.select_dtypes(include="number").corr()["price_lakhs"]
print(correlations)

strongest_feature = correlations.drop("price_lakhs").abs().idxmax()
print("Strongest correlation:", strongest_feature, "=", correlations[strongest_feature])

area_sqft         0.991111
bedrooms          0.934684
bathrooms         0.866851
age_years        -0.770444
price_lakhs       1.000000
price_per_sqft    0.987987
Name: price_lakhs, dtype: float64
Strongest correlation: area_sqft = 0.9911112626407953

---
## Section C: Missing Values

**Q15.** Run the cell below to create `df_messy`, a version of the housing data with some missing values
inserted. Then print how many missing values exist in **each column**.

In [ ]:
# Run this first — do not modify
df_messy = df.copy()
df_messy.loc[[2, 7, 15], "area_sqft"] = np.nan
df_messy.loc[[1, 9], "bathrooms"] = np.nan
df_messy.loc[[4, 11, 18], "price_lakhs"] = np.nan
df_messy

,area_sqft,bedrooms,bathrooms,age_years,locality,price_lakhs,price_per_sqft,size_category
0,650.0,1,1.0,5,Vaishali Nagar,32.0,4923.076923,Small
1,800.0,2,NaN,12,Malviya Nagar,42.0,5250.000000,Small
2,NaN,3,2.0,8,C-Scheme,78.0,6500.000000,Medium
3,950.0,2,2.0,20,Mansarovar,55.0,5789.473684,Medium
4,1500.0,3,2.0,3,C-Scheme,NaN,7000.000000,Large
5,700.0,1,1.0,15,Malviya Nagar,35.0,5000.000000,Small
6,1100.0,2,2.0,10,Vaishali Nagar,68.0,6181.818182,Medium
7,NaN,4,3.0,2,C-Scheme,145.0,8055.555556,Large
8,900.0,2,1.0,18,Mansarovar,52.0,5777.777778,Medium
9,1300.0,3,NaN,7,Malviya Nagar,82.0,6307.692308,Medium
10,600.0,1,1.0,25,Mansarovar,28.0,4666.666667,Small
11,1050.0,2,2.0,9,Vaishali Nagar,NaN,5904.761905,Medium
12,1600.0,3,2.0,4,C-Scheme,115.0,7187.500000,Large
13,750.0,2,1.0,14,Malviya Nagar,40.0,5333.333333,Small
14,1400.0,3,2.0,6,C-Scheme,98.0,7000.000000,Large
15,NaN,2,2.0,11,Vaishali Nagar,58.0,5800.000000,Medium
16,1250.0,3,2.0,8,Malviya Nagar,75.0,6000.000000,Medium
17,850.0,2,1.0,16,Mansarovar,48.0,5647.058824,Small
18,1700.0,4,3.0,1,C-Scheme,NaN,7941.176471,Large
19,950.0,2,2.0,13,Vaishali Nagar,56.0,5894.736842,Medium

In [ ]:
# Q15
print(df_messy.isna().sum())

area_sqft         3
bedrooms          0
bathrooms         2
age_years         0
locality          0
price_lakhs       3
price_per_sqft    0
size_category     0
dtype: int64

**Q16.** Create `df_filled`, a copy of `df_messy` where:
- missing `area_sqft` values are filled with the **column median**
- missing `bathrooms` values are filled with the **column mode** (most frequent value)
- missing `price_lakhs` values are filled with the **mean price of the same locality** (hint: `.groupby()` +
  `.transform()`, or fill locality-by-locality)

In [ ]:
# Q16
df_filled = df_messy.copy()

df_filled["area_sqft"] = df_filled["area_sqft"].fillna(df_filled["area_sqft"].median())
df_filled["bathrooms"] = df_filled["bathrooms"].fillna(df_filled["bathrooms"].mode()[0])

locality_mean_price = df_filled.groupby("locality")["price_lakhs"].transform("mean")
df_filled["price_lakhs"] = df_filled["price_lakhs"].fillna(locality_mean_price)

print(df_filled)

    area_sqft  bedrooms  bathrooms  age_years        locality  price_lakhs  \
0       650.0         1        1.0          5  Vaishali Nagar         32.0
1       800.0         2        2.0         12   Malviya Nagar         42.0
2       950.0         3        2.0          8        C-Scheme         78.0
3       950.0         2        2.0         20      Mansarovar         55.0
4      1500.0         3        2.0          3        C-Scheme        109.0
5       700.0         1        1.0         15   Malviya Nagar         35.0
6      1100.0         2        2.0         10  Vaishali Nagar         68.0
7       950.0         4        3.0          2        C-Scheme        145.0
8       900.0         2        1.0         18      Mansarovar         52.0
9      1300.0         3        2.0          7   Malviya Nagar         82.0
10      600.0         1        1.0         25      Mansarovar         28.0
11     1050.0         2        2.0          9  Vaishali Nagar         53.5
12     1600.0         3        2.0          4        C-Scheme        115.0
13      750.0         2        1.0         14   Malviya Nagar         40.0
14     1400.0         3        2.0          6        C-Scheme         98.0
15      950.0         2        2.0         11  Vaishali Nagar         58.0
16     1250.0         3        2.0          8   Malviya Nagar         75.0
17      850.0         2        1.0         16      Mansarovar         48.0
18     1700.0         4        3.0          1        C-Scheme        109.0
19      950.0         2        2.0         13  Vaishali Nagar         56.0

    price_per_sqft size_category
0      4923.076923         Small
1      5250.000000         Small
2      6500.000000        Medium
3      5789.473684        Medium
4      7000.000000         Large
5      5000.000000         Small
6      6181.818182        Medium
7      8055.555556         Large
8      5777.777778        Medium
9      6307.692308        Medium
10     4666.666667         Small
11     5904.761905        Medium
12     7187.500000         Large
13     5333.333333         Small
14     7000.000000         Large
15     5800.000000        Medium
16     6000.000000        Medium
17     5647.058824         Small
18     7941.176471         Large
19     5894.736842        Medium

**Q17.** Instead of filling, create `df_complete_only` by **dropping** any row in `df_messy` that has at least
one missing value. How many rows are left compared to the original 20?

In [ ]:
# Q17
df_complete_only = df_messy.dropna()

print("Rows left:", len(df_complete_only))
print("Rows removed:", len(df) - len(df_complete_only))

Rows left: 12
Rows removed: 8

---
## Section D: Mini Challenge

**Q18.** Without using any missing-value dataset — using the original clean `df` — answer in one line of code
each:
- Which locality has the **most expensive average house**?
- Which locality has the **most number of houses listed**?
- What is the price range (max − min) of houses with **exactly 2 bedrooms**?

In [ ]:
# Q18
print(df.groupby("locality")["price_lakhs"].mean().idxmax())
print(df["locality"].value_counts().idxmax())
print(df.loc[df["bedrooms"] == 2, "price_lakhs"].max() - df.loc[df["bedrooms"] == 2, "price_lakhs"].min())

C-Scheme
C-Scheme
28

**Q19. (Challenge)** Write a single block of code that, for each locality, prints a one-line summary in this
exact format:

```
Malviya Nagar: 5 houses, avg price 55.4 lakhs, avg area 1040 sqft
```

(Hint: loop over `df["locality"].unique()`, or use `.groupby()` and iterate over the result with `.iterrows()`
on a summary DataFrame — both approaches are fine.)

In [ ]:
# Q19
summary = df.groupby("locality").agg(
    houses=("locality", "size"),
    avg_price=("price_lakhs", "mean"),
    avg_area=("area_sqft", "mean")
)

for locality, row in summary.iterrows():
    print(f"{locality}: {row['houses']} houses, avg price {row['avg_price']:.1f} lakhs, avg area {row['avg_area']:.0f} sqft")

C-Scheme: 6.0 houses, avg price 112.7 lakhs, avg area 1533 sqft
Malviya Nagar: 5.0 houses, avg price 54.8 lakhs, avg area 960 sqft
Mansarovar: 4.0 houses, avg price 45.8 lakhs, avg area 825 sqft
Vaishali Nagar: 5.0 houses, avg price 55.2 lakhs, avg area 950 sqft

---
## Done?

Save your notebook and bring it to the start of Lab 2 — we'll review a few of these together before moving on to
building your first regression model.